CREATE SEQUENCE public.seq_edi_pessoa;

ALTER SEQUENCE public.seq_edi_pessoa
    OWNER TO edi;

--------------------------------------
	
CREATE SEQUENCE public.seq_edi_client;

ALTER SEQUENCE public.seq_edi_client
    OWNER TO edi;
	
--------------------------------------
	
CREATE SEQUENCE public.seq_edi_clicbl;

ALTER SEQUENCE public.seq_edi_clicbl
    OWNER TO edi;
	
--------------------------------------	

CREATE SEQUENCE public.seq_edi_cclprc;

ALTER SEQUENCE public.seq_edi_cclprc
    OWNER TO edi;
	
--------------------------------------		

CREATE SEQUENCE public.seq_edi_cblnoc;

ALTER SEQUENCE public.seq_edi_cblnoc
    OWNER TO edi;

--------------------------------------		

CREATE SEQUENCE public.seq_edi_clpcco;

ALTER SEQUENCE public.seq_edi_clpcco
    OWNER TO edi;